[package]
name = "xiaoai"
version = "0.2.0"
description = "Utils to remote XiaoAi; 远程操作小爱同学（小爱音箱）"
documentation = "https://docs.rs/xiaoai"
exclude = ["*.json"]
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
api_req = { version = "0.5" }
base64 = "0.22"
dotenvy.workspace = true
hex = "0.4"
md5 = { version = "0.8" }
rand.workspace = true
reqwest = { version = "0.13", features = ["cookies"] }
serde.workspace = true
serde_json.workspace = true
sha1 = "0.11"
thiserror = "2.0"

[dev-dependencies]
tokio.workspace = true
