[package]
name = "xiaoai_llm"
version = "0.1.0"
description = "Utils to power XiaoAi with LLM; 使用大型语言模型为小爱同学提供更多功能"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["macros"] }
dotenvy.workspace = true
mime_guess = "2"
rand.workspace = true
regex = "1"
tokio = { workspace = true, features = ["signal"] }
tower = { version = "0.5" }
tower-http = { version = "0.7", features = ["fs"] }
urlencoding = "2"
walkdir = "2.5"
xiaoai = { path = "../rXiaoai", version = "0.2" }

[dev-dependencies]
tempfile = "3.27.0"
tower = { version = "0.5", features = ["util"] }
