[package]
name = "xiaoai_llm"
version = "0.1.0"
edition = "2024"
description = "Utils to power XiaoAi with LLM; 使用大型语言模型为小爱同学提供更多功能"
repository = "https://github.com/kingwingfly/rXiaoAiLLM"

[dependencies]
tokio = { version = "1.44.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
api_req = { version = "0.3.0" }
xiaoai = { path = "../rXiaoAi", version = "0.1.0-alpha.7" }
anyhow = "1.0.97"
regex = "1.11.1"
urlencoding = "2.1.3"
